### ISSUE TITLE
Cell Phone Silence/Unsilenced

### ISSUE THREAD

**Issue by cisconetdude** [ColonolNutty/Sims4CommunityLibrary#19]
With S4CL after last Sims 4 Patch this button is gone.  Removing the Library brought all buttons back.  The change color on the cell phone was still there.  This also broke a button added at the top for Basemental Drugs, the find CO-Star button.

**Comment by ColonolNutty** [comment]
In order for S4CL to provide the custom Cheat menu, it filters out any interactions tagged as a Cheat, if they are tagged as a cheat, they will appear in the Shift+Click menu instead. Hold Shift and click on the phone icon to access this menu.

If you are talking about the Silence Phone icon and you are using Wicked Whims, Wicked Whims is the cause of this, not S4CL. In vanilla Sims 4, the Silence Phone icon is NOT flagged as a cheat interaction, however Wicked Whims flags it as a Cheat interaction for unknown reasons. Since vanilla Sims 4 does not normally have a Cheat menu for the phone, there should be ZERO reason for Wicked Whims to add or alter any interactions for the phone as Cheat interactions, yet it does.

In the next test build of S4CL I have accounted for this annoyance caused by Wicked Whims. I do this by hardcoding it so that the silence phone interaction will always appear regardless of its Cheat status.

If you want a true fix for it, then complain to Turbodriver for making a seemingly pointless alteration to an interaction that WickedWhims has no business altering.

If you do not wish to wait for the S4CL test build, then you may run the following commands to do the same functionality ‘s4clib.silence_phone’ and ‘s4clib.unsilence_phone’
